name: test
on: [push, pull_request]

jobs:
  test:
    name: Node.js ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 14]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Setup
        run: |
          npm install
          npm test
          npm link
          mkdir ../js-app && mkdir ../ts-app

      - name: Test create-ink-app with JavaScript
        working-directory: ../js-app
        run: |
          create-ink-app
          npm test

      - name: Test create-ink-app with TypeScript
        working-directory: ../ts-app
        run: |
          create-ink-app --typescript
          npm test
